### ISSUE TITLE
issue creating the json module with readout.app_confgen module

### ISSUE THREAD

**Issue by pmendezl** [DUNE-DAQ/readout#57]
Using a standard Centos7 machine I am having problems while trying to create a json file:

python -m readout.app_confgen -n 10 -t 1 -d ./frames.bin readout_conf1.json
           },
            {
                "data": {
                    "disable_data_storage": false,
                    "run": 333,
                    "trigger_interval_ticks": 64000000
                },
                "match": "fake_source"
            }
        ]
    },
    "entry_state": "CONFIGURED",
    "exit_state": "RUNNING",
    "id": "start"
}
Traceback (most recent call last):
  File "/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases/dunedaq-v2.3.0/externals/python/v3_8_3b/Linux64bit+3.10-2.17/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/dune.opensciencegrid.org/dunedaq/DUNE/releases/dunedaq-v2.3.0/externals/python/v3_8_3b/Linux64bit+3.10-2.17/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/build/readout/python/readout/app_confgen.py", line 184, in <module>
    cli()
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/dbt-pyvenv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/dbt-pyvenv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/dbt-pyvenv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/dbt-pyvenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/build/readout/python/readout/app_confgen.py", line 174, in cli
    f.write(generate(
  File "/home/pmendez/workspace/DUNE-Release/MyTopDir/build/readout/python/readout/app_confgen.py", line 130, in generate
    emptypars = rccmd.EmptyParams()
AttributeError: module 'dunedaq.rcif.cmd' has no attribute 'EmptyParams'

I am using the set of instructions included at the document: "Instructions for setting up a v2.4.0 development environment". The problem is not reproducible with minidaqapp or wityh dfmodules, which work as expected.

Thanks so much

**Comment by roland-sipos** [comment]
Hi @pmendezl .
I'm puzzled as the error is from `rcif` . I'm wondering if this is related to the environment or the instructions, but not to `readout`:

AttributeError: module 'dunedaq.rcif.cmd' has no attribute 'EmptyParams'

**Comment by pmendezl** [comment]
Hi Roland,

have you been able to reproduce the problem? maybe I am just not using the proper instructions. How are you using it?

Thanks!!
Patricia

On 16 Mar 2021, at 16:41, Roland Sipos ***@***.******@***.***>> wrote:



Hi @pmendezl<https://github.com/pmendezl> .
I'm puzzled as the error is from rcif . I'm wondering if this is related to the environment or the instructions, but not to readout:

AttributeError: module 'dunedaq.rcif.cmd' has no attribute 'EmptyParams'
